name: Repo Release Monitor

on:
  schedule:
    - cron: "0 0 * * 1-5"  # every UTC 00:00 MON-FRI

permissions:
  contents: write

jobs:
  check_and_notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version-file: '.python-version'
      - uses: astral-sh/setup-uv@v7
      - name: Install the project
        run: uv sync --locked --all-extras --dev
      - name: Run the main application
        run: uv run main.py --log_level DEBUG
        env:
          WEBHOOK__URL: ${{ secrets.WEBHOOK_URL }}
      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add state.yaml

          if ! git diff-index --quiet --cached HEAD --; then
            git commit -m "chore(bot): Update state.yaml"
            git push
          fi
